name: Deploy Frontend

on:
  push:
    branches:
      - main  # or whichever branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16  # Ensure this matches your project's Node.js version

    - name: Install dependencies
      run: |
        cd "Food Delivery/frontend"  # Navigate to the frontend folder inside "Food Delivery"
        npm install

    - name: Build project
      run: |
        cd "Food Delivery/frontend"
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Food\ Delivery/frontend/dist  # Correct path for the "dist" directory
